GCC: accessing TransportParameters enum class members require using the class prefix
GCC does not allow to directly use the members of the TransportParameters enum class
without explicitely referring to the class name.

GCC build error shows several instances like this one:
../../net/third_party/quiche/src/quic/core/crypto/transport_parameters.cc: In function ‘bool quic::SerializeTransportParameters(const quic::TransportParameters&, std::vector<unsigned char>*)’:
../../net/third_party/quiche/src/quic/core/crypto/transport_parameters.cc:393:31: error: ‘kOriginalConnectionId’ was not declared in this scope

Bug: chromium:819294
Change-Id: Ib793d7b5718213a10537acf5cfa2103e38a5594b